-- Active search: open roles from companies on Ezzy's target list, read from
-- the open job-board feeds those companies publish (Greenhouse, Lever,
-- Ashby, SmartRecruiters, Workable, Rippling). See supabase/seed/README.md
-- for how the list was built and which sources are deliberately excluded.
--
-- job_sources: one row per company feed. Add or switch off a company here,
-- no deploy needed. job_listings: one row per open role, refreshed by
-- api/jobs-sync.js (nightly cron). Descriptions are not stored; the full
-- posting is fetched from the company's feed only when someone asks for a
-- fit check, and then it becomes a career_opportunities row like any other.

create table if not exists job_sources (
  id uuid primary key default gen_random_uuid(),
  company text not null unique,
  ats text not null check (ats in ('greenhouse','lever','ashby','smartrecruiters','workable','rippling')),
  slug text not null,
  active boolean not null default true,
  last_synced_at timestamptz,
  last_count int,
  last_error text,
  created_at timestamptz not null default now(),
  unique (ats, slug)
);
alter table job_sources enable row level security;
grant select, insert, update, delete on job_sources to service_role;

create table if not exists job_listings (
  id uuid primary key default gen_random_uuid(),
  company text not null,
  ats text not null,
  slug text not null,
  external_id text not null,
  title text not null,
  location text,
  remote boolean not null default false,
  department text,
  url text not null,
  posted_at timestamptz,
  family text,          -- same role families as the rubrics, derived from the title
  level text,           -- only when the title states it
  active boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  title_tsv tsvector generated always as (to_tsvector('english', title)) stored,
  unique (ats, slug, external_id)
);
create index if not exists job_listings_title_idx on job_listings using gin (title_tsv);
create index if not exists job_listings_active_idx on job_listings (active, family, posted_at desc);
create index if not exists job_listings_source_idx on job_listings (ats, slug, last_seen_at);

alter table job_listings enable row level security;
-- Public postings, readable by any signed-in user; only the sync writes.
create policy "job_listings: read" on job_listings for select to authenticated using (true);
grant select on job_listings to authenticated;
grant select, insert, update, delete on job_listings to service_role;

insert into job_sources (company, ats, slug) values
  ('15Five', 'lever', '15five'),
  ('AbbVie', 'smartrecruiters', 'abbvie'),
  ('Abnormal Security', 'greenhouse', 'abnormalsecurity'),
  ('Affirm', 'greenhouse', 'affirm'),
  ('Airbnb', 'greenhouse', 'airbnb'),
  ('Airtable', 'greenhouse', 'airtable'),
  ('Aledade', 'lever', 'aledade'),
  ('Amwell', 'greenhouse', 'amwell'),
  ('Anduril', 'greenhouse', 'andurilindustries'),
  ('Angi', 'ashby', 'angi'),
  ('Anthropic', 'greenhouse', 'anthropic'),
  ('Asana', 'greenhouse', 'asana'),
  ('Ashby', 'ashby', 'ashby'),
  ('Attentive', 'greenhouse', 'attentive'),
  ('Axonius', 'greenhouse', 'axonius'),
  ('Benchling', 'ashby', 'benchling'),
  ('BetterUp', 'ashby', 'betterup'),
  ('BigID', 'greenhouse', 'bigid'),
  ('Block', 'greenhouse', 'block'),
  ('Braze', 'greenhouse', 'braze'),
  ('Brex', 'greenhouse', 'brex'),
  ('Canva', 'smartrecruiters', 'canva'),
  ('Carbon Health', 'rippling', 'carbon-health'),
  ('Cedar', 'greenhouse', 'careportalinc'),
  ('Cerebras', 'ashby', 'cerebras'),
  ('Chainalysis', 'ashby', 'chainalysis-careers'),
  ('Character.AI', 'ashby', 'character'),
  ('Chime', 'greenhouse', 'chime'),
  ('CircleCI', 'greenhouse', 'circleci'),
  ('ClickUp', 'ashby', 'clickup'),
  ('Cloudflare', 'greenhouse', 'cloudflare'),
  ('Cockroach Labs', 'greenhouse', 'cockroachlabs'),
  ('Cohere', 'ashby', 'cohere'),
  ('Coinbase', 'greenhouse', 'coinbase'),
  ('Compass', 'greenhouse', 'urbancompass'),
  ('Confluent', 'ashby', 'confluent'),
  ('CoreWeave', 'greenhouse', 'coreweave'),
  ('Culture Amp', 'greenhouse', 'cultureamp'),
  ('Cursor / Anysphere', 'ashby', 'cursor'),
  ('Databricks', 'greenhouse', 'databricks'),
  ('Datadog', 'greenhouse', 'datadog'),
  ('Decagon', 'ashby', 'decagon'),
  ('DigitalOcean', 'greenhouse', 'digitalocean98'),
  ('Docker', 'ashby', 'docker'),
  ('DoorDash', 'greenhouse', 'doordashusa'),
  ('Drata', 'ashby', 'drata'),
  ('Duolingo', 'greenhouse', 'duolingo'),
  ('Elastic', 'greenhouse', 'elastic'),
  ('ElevenLabs', 'ashby', 'elevenlabs'),
  ('Epic Games', 'greenhouse', 'epicgames'),
  ('Faire', 'greenhouse', 'faire'),
  ('Fastly', 'greenhouse', 'fastly'),
  ('Figma', 'greenhouse', 'figma'),
  ('Figure AI', 'greenhouse', 'figureai'),
  ('Fireworks AI', 'ashby', 'fireworks'),
  ('Flatiron Health', 'greenhouse', 'flatironhealth'),
  ('Flexe', 'greenhouse', 'flexe'),
  ('Flexport', 'greenhouse', 'flexport'),
  ('Gemini', 'greenhouse', 'gemini'),
  ('GitLab', 'greenhouse', 'gitlab'),
  ('Glean', 'greenhouse', 'gleanwork'),
  ('Glossier', 'greenhouse', 'glossier'),
  ('GOAT', 'greenhouse', 'goatgroup'),
  ('Gong', 'greenhouse', 'gongio'),
  ('Gopuff', 'lever', 'gopuff'),
  ('Grafana Labs', 'greenhouse', 'grafanalabs'),
  ('Greenhouse', 'greenhouse', 'greenhouse'),
  ('Gusto', 'greenhouse', 'gusto'),
  ('Harness', 'greenhouse', 'harnessinc'),
  ('Harvey', 'ashby', 'harvey'),
  ('Headspace', 'greenhouse', 'hs'),
  ('Hearst', 'greenhouse', 'hearst'),
  ('Hims & Hers', 'ashby', 'hims-and-hers'),
  ('Hootsuite', 'greenhouse', 'hootsuite'),
  ('Hopper', 'ashby', 'hopper'),
  ('Houzz', 'lever', 'houzz'),
  ('HubSpot', 'greenhouse', 'hubspotjobs'),
  ('Hugging Face', 'workable', 'huggingface'),
  ('Illumio', 'ashby', 'illumio'),
  ('Included Health', 'lever', 'includedhealth'),
  ('Insitro', 'ashby', 'insitro'),
  ('Instacart', 'greenhouse', 'instacart'),
  ('Intercom', 'greenhouse', 'intercom'),
  ('Iterable', 'ashby', 'iterable'),
  ('Jane Street', 'greenhouse', 'janestreet'),
  ('Klaviyo', 'greenhouse', 'klaviyo'),
  ('Komodo Health', 'greenhouse', 'komodohealth'),
  ('Kraken', 'ashby', 'kraken.com'),
  ('LangChain', 'ashby', 'langchain'),
  ('Later', 'greenhouse', 'later'),
  ('Lattice', 'greenhouse', 'lattice'),
  ('LaunchDarkly', 'greenhouse', 'launchdarkly'),
  ('Linear', 'ashby', 'linear'),
  ('Lyft', 'greenhouse', 'lyft'),
  ('Match Group', 'lever', 'matchgroup'),
  ('Maven Clinic', 'greenhouse', 'mavenclinic'),
  ('Mercury', 'greenhouse', 'mercury'),
  ('Mindbody', 'greenhouse', 'mindbody'),
  ('Mistral AI', 'ashby', 'mistral.ai'),
  ('Modal', 'ashby', 'modal'),
  ('MongoDB', 'greenhouse', 'mongodb'),
  ('NBCUniversal', 'smartrecruiters', 'NBCUniversal3'),
  ('Netskope', 'greenhouse', 'netskope'),
  ('New Relic', 'greenhouse', 'newrelic'),
  ('Notion', 'ashby', 'notion'),
  ('OfferUp', 'greenhouse', 'offerup'),
  ('Okta', 'greenhouse', 'okta'),
  ('One Medical', 'greenhouse', 'onemedical'),
  ('OneTrust', 'greenhouse', 'onetrust'),
  ('OpenAI', 'ashby', 'openai'),
  ('Opendoor', 'rippling', 'opendoor'),
  ('Oscar Health', 'greenhouse', 'oscar'),
  ('Oyster', 'ashby', 'oyster'),
  ('Palantir', 'lever', 'palantir'),
  ('PathAI', 'greenhouse', 'pathai'),
  ('Peloton', 'greenhouse', 'peloton'),
  ('Perplexity', 'ashby', 'perplexity'),
  ('Pinterest', 'greenhouse', 'pinterest'),
  ('Plaid', 'ashby', 'plaid'),
  ('PlanetScale', 'greenhouse', 'planetscale'),
  ('Poshmark', 'ashby', 'poshmark'),
  ('Pure Storage', 'greenhouse', 'purestorage'),
  ('R/GA', 'greenhouse', 'rga'),
  ('Ramp', 'ashby', 'ramp'),
  ('Recursion', 'greenhouse', 'recursionpharmaceuticals'),
  ('Reddit', 'greenhouse', 'reddit'),
  ('Replit', 'ashby', 'replit'),
  ('Riot Games', 'greenhouse', 'riotgames'),
  ('Rippling', 'rippling', 'rippling'),
  ('Ro', 'lever', 'ro'),
  ('Robinhood', 'greenhouse', 'robinhood'),
  ('Roblox', 'greenhouse', 'roblox'),
  ('Roku', 'greenhouse', 'roku'),
  ('Rover', 'lever', 'rover'),
  ('Rubrik', 'greenhouse', 'rubrik'),
  ('Runway', 'ashby', 'runway-ml'),
  ('Scale AI', 'greenhouse', 'scaleai'),
  ('Schrödinger', 'greenhouse', 'schrdinger'),
  ('SentinelOne', 'greenhouse', 'sentinellabs'),
  ('Sentry', 'ashby', 'sentry'),
  ('ServiceNow', 'smartrecruiters', 'servicenow'),
  ('Shield AI', 'lever', 'shieldai'),
  ('Sierra', 'ashby', 'sierra'),
  ('Snowflake', 'ashby', 'snowflake'),
  ('Snyk', 'ashby', 'snyk'),
  ('SoFi', 'greenhouse', 'sofi'),
  ('Sony Music Entertainment', 'greenhouse', 'sonymusicentertainment'),
  ('SpaceX', 'greenhouse', 'spacex'),
  ('Spotify', 'lever', 'spotify'),
  ('Sprout Social', 'greenhouse', 'sproutsocial'),
  ('StockX', 'greenhouse', 'stockx'),
  ('Stripe', 'greenhouse', 'stripe'),
  ('Supabase', 'ashby', 'supabase'),
  ('Take-Two Interactive', 'greenhouse', 'taketwo'),
  ('Temporal', 'ashby', 'temporal'),
  ('Tenable', 'greenhouse', 'tenableinc'),
  ('The Athletic', 'lever', 'theathletic'),
  ('The New York Times', 'greenhouse', 'thenewyorktimes'),
  ('Thinking Machines Lab', 'ashby', 'thinkingmachines'),
  ('Thoughtworks', 'greenhouse', 'thoughtworks'),
  ('Thumbtack', 'ashby', 'thumbtack'),
  ('Tia', 'greenhouse', 'tia'),
  ('Toast', 'greenhouse', 'toast'),
  ('Together AI', 'greenhouse', 'togetherai'),
  ('TravelPerk', 'ashby', 'perk'),
  ('TripAdvisor', 'greenhouse', 'tripadvisor'),
  ('Twilio', 'greenhouse', 'twilio'),
  ('Twitch', 'greenhouse', 'twitch'),
  ('Uber Freight', 'greenhouse', 'uberfreight'),
  ('Vanta', 'ashby', 'vanta'),
  ('Veeva Systems', 'lever', 'veeva'),
  ('Vercel', 'greenhouse', 'vercel'),
  ('Verkada', 'greenhouse', 'verkada'),
  ('VML', 'greenhouse', 'wundermanthompson'),
  ('Vox Media', 'greenhouse', 'voxmedia'),
  ('Warner Music Group', 'lever', 'wmg'),
  ('Waymo', 'greenhouse', 'waymo'),
  ('Webflow', 'greenhouse', 'webflow'),
  ('Wiz', 'greenhouse', 'wizinc'),
  ('WPP', 'greenhouse', 'wpp'),
  ('xAI', 'greenhouse', 'xai'),
  ('Zapier', 'ashby', 'zapier'),
  ('Zocdoc', 'greenhouse', 'zocdoc'),
  ('Zoox', 'lever', 'zoox'),
  ('Zscaler', 'greenhouse', 'zscaler')
on conflict (company) do nothing;
